#!/bin/sh
#
### BEGIN INIT INFO
# Provides: janus
# Required-Start: $syslog $network $local_fs $time $named $all
# Required-Stop: $syslog $network $local_fs
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: Start the Janus WebRTC Gateway
# Description: Start the Janus WebRTC Gateway.
### END INIT INFO

PATH=/sin:/bin:/usr/sbin:/usr/bin
DAEMON=/opt/janus/bin/janus
NAME=janus
DESC=janus
LOG=/var/log/daemon.log
HOMEDIR=/var/run
PIDFILE="$HOMEDIR/$NAME.pid"

test -f "$DAEMON" || exit 0

set -e

OPTIONS=""

case "$1" in
start)
  # Check the PID file exists and check the actual status of process
  PID=`ps -ef | grep "$DAEMON" | grep -v grep | awk '{print $2}'`
  if [ -n "$PID" ] ; then
    echo "$NAME is already running on PID $PID"
  else
    rm -f "$PIDFILE"
    echo -n "Starting $NAME"
    /sbin/start-stop-daemon -S -q -p "$PIDFILE" -x "$DAEMON" -- "$OPTIONS" \
     >> "$LOG" 2>&1 || echo -n " ...already running"
    echo "."
  fi
  ;;
stop)
  echo -n "Stopping $NAME"
  /sbin/start-stop-daemon -o -K -q -p "$PIDFILE" -x "$DAEMON"
  echo "."
  ;;
restart)
  echo -n "Restarting $NAME"
  /sbin/start-stop-daemon -o -K -q -p "$PIDFILE" -x "$DAEMON"
  sleep 10
  /sbin/start-stop-daemon -S -q -p "$PIDFILE" -x "$DAEMON" -- "$OPTIONS" \
   >> "$LOG" 2>&1 || echo -n " ...already running"
  echo "."
  ;;
status)
  echo -n "Status of $NAME: "
  if [ ! -r "$PIDFILE" ]; then
    echo "not running."
    exit 3
  fi
  if read pid < "$PIDFILE" && ps -p "$pid" > /dev/null 2>&1 ; then
    echo "running."
    exit 0
  fi
  echo "not running (but $PIDFILE exists)."
  exit 1
  ;;
*)
  echo "Usage: /etc/init.d/$NAME {start|stop|restart|status}" >&2
  exit1
  ;;
esac
exit 0
